-- Generated by scripts/history/build-history-sql.ts from scripts/history/lift-log.json.
-- Imports the Obsidian Lift Log (05/08–21/09/2026). Idempotent: safe to re-run.

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Push-Up (flat palm)', 'Upper Body — Push (Horizontal)', 'NO', 'bodyweight', 'upper', FALSE, 'Flat-palm loading. Left wrist (TFCC).') ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Tricep Pushdown (straight bar)', 'Arms', 'NO', 'cable', 'upper', FALSE, 'Straight-bar pushdown. Left wrist (TFCC).') ON CONFLICT DO NOTHING;

UPDATE exercises SET substitute_ids = ARRAY(SELECT id FROM exercises WHERE slug IN ('rope-pushdown')) WHERE name = 'Tricep Pushdown (straight bar)' AND created_by IS NULL;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Machine Chest Fly', 'Upper Body — Push (Horizontal)', 'YES', 'machine', 'upper', FALSE, NULL) ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Machine Tricep Press', 'Arms', 'YES', 'machine', 'upper', FALSE, NULL) ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Machine Torso Rotation', 'Core', 'YES', 'machine', 'upper', FALSE, NULL) ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Machine Abdomen Crunch', 'Core', 'YES', 'machine', 'upper', FALSE, NULL) ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Machine Abdomen Crunch (lower)', 'Core', 'YES', 'machine', 'upper', FALSE, NULL) ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Ab Crunch (Matrix)', 'Core', 'YES', 'machine', 'upper', FALSE, NULL) ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Ab Crunch (Life Fitness)', 'Core', 'YES', 'machine', 'upper', FALSE, NULL) ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Machine Lateral Raise', 'Upper Body — Push (Vertical)', 'YES', 'machine', 'upper', FALSE, NULL) ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('Forearm / Wrist Curl', 'Arms', 'YES', 'dumbbell', 'upper', FALSE, NULL) ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('DB Pullover', 'Upper Body — Pull (Vertical)', 'YES', 'dumbbell', 'upper', FALSE, NULL) ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, status, equipment, body_region, is_compound, blocked_reason) VALUES ('DB Romanian Deadlift', 'Lower Body — Posterior Chain', 'NO', 'dumbbell', 'lower', TRUE, 'Lower back pain on 21/09 — removed until the back is symptom-free.') ON CONFLICT DO NOTHING;

INSERT INTO constraints (user_id, region, rule, blocked_patterns) VALUES ('evilpotato345@gmail.com', 'Lower back · lumbar irritation', 'Logged 19/08, DB RDL brought on pain 21/09. No loaded spinal hinging in any session (A, B or C) until symptom-free. Radiating pain below the knee, numbness or foot weakness = physio first.', ARRAY['deadlift', 'rdl', 'good morning', 'bent over row', 'pendlay row', 'back extension', 'hyperextension']::TEXT[]) ON CONFLICT (user_id, region) WHERE user_id IS NOT NULL DO UPDATE SET rule = EXCLUDED.rule, blocked_patterns = EXCLUDED.blocked_patterns;

INSERT INTO constraints (user_id, region, rule, blocked_patterns) VALUES ('evilpotato345@gmail.com', 'Thyroid · Hashimoto''s', 'Hypothyroid: recovery is the limiter, not effort. Sleep and protein come before load.', ARRAY[]::TEXT[]) ON CONFLICT (user_id, region) WHERE user_id IS NOT NULL DO UPDATE SET rule = EXCLUDED.rule, blocked_patterns = EXCLUDED.blocked_patterns;

WITH s AS (
  INSERT INTO sessions (user_id, date, session_name, session_type, notes, status, week_number, block_number)
  SELECT 'evilpotato345@gmail.com', '2026-08-05', 'Session C · Chest, Triceps & Core', 'C', 'Machine gym (not Al Reef). Rest periods too short (60–90 s, including compounds) — paced like a circuit, which is why the horizontal press top set collapsed to 5. Pre-session 8 min walk + 4 min run. Garmin: 63 min, avg HR 132, max 163, 351 kcal. Next C: 6 exercises, 3 min rest on presses, open horizontal press at 20/side and rope pushdown at 15.', 'DONE', 1, '1'
  WHERE NOT EXISTS (SELECT 1 FROM sessions WHERE user_id = 'evilpotato345@gmail.com' AND date = '2026-08-05' AND session_type = 'C')
  RETURNING id
)
INSERT INTO session_exercises (session_id, exercise_id, sets, reps, weight, set_details, rpe, notes, order_index)
SELECT s.id, (SELECT id FROM exercises WHERE name = v.name AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1), v.sets, v.reps, v.weight::numeric, v.details::jsonb, v.rpe::numeric, v.notes, v.ord
FROM s CROSS JOIN (VALUES
  ('Push-Up (flat palm)', 2, 12, 0.00, '[{"reps":12,"weight":0,"platesKg":null,"rpe":null,"type":"working","flags":["blocked_override"]},{"reps":10,"weight":0,"platesKg":null,"rpe":8,"type":"working","flags":["blocked_override"]}]', 8, 'Flat palm — retired movement (wrist).', 0),
  ('Iso-Lateral Horizontal Press', 4, 10, 28.20, '[{"reps":10,"weight":23.2,"platesKg":15,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":5,"weight":28.2,"platesKg":20,"rpe":null,"type":"working","flags":[]},{"reps":7,"weight":28.2,"platesKg":20,"rpe":null,"type":"working","flags":[]},{"reps":8,"weight":23.2,"platesKg":15,"rpe":9,"type":"working","flags":[]}]', 9, 'Carriage not yet known at the time; true load = plates + 8.2.', 1),
  ('Rope Pushdown', 2, 15, 12.50, '[{"reps":15,"weight":10,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":10,"weight":12.5,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, 'Set 1 at 15 reps — too light.', 2),
  ('Iso-Lateral Decline Press', 3, 10, 30.20, '[{"reps":7,"weight":30.2,"platesKg":27.5,"rpe":null,"type":"working","flags":[]},{"reps":7,"weight":30.2,"platesKg":27.5,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":25.2,"platesKg":22.5,"rpe":9,"type":"working","flags":[]}]', 9, 'Best loading of the session.', 3),
  ('Tricep Pushdown (straight bar)', 3, 12, 17.50, '[{"reps":12,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":["blocked_override"]},{"reps":12,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":["blocked_override"]},{"reps":10,"weight":17.5,"platesKg":null,"rpe":8,"type":"working","flags":["blocked_override"]}]', 8, 'Straight bar — retired movement (wrist).', 4),
  ('Machine Chest Fly', 3, 15, 35.00, '[{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":9,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":15,"weight":27.5,"platesKg":null,"rpe":9,"type":"working","flags":[]}]', 9, NULL, 5),
  ('Machine Tricep Press', 3, 12, 57.50, '[{"reps":12,"weight":42.5,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":50,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":57.5,"platesKg":null,"rpe":9,"type":"working","flags":[]}]', 9, 'Clean ascending load.', 6),
  ('Machine Torso Rotation', 3, 12, 42.50, '[{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":42.5,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":42.5,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, NULL, 7),
  ('Machine Abdomen Crunch', 3, 10, 35.00, '[{"reps":10,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":35,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, NULL, 8),
  ('Machine Abdomen Crunch (lower)', 3, 10, 27.00, '[{"reps":10,"weight":27,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":27,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":27,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, NULL, 9)
) AS v(name, sets, reps, weight, details, rpe, notes, ord);

INSERT INTO daily_check_ins (user_id, date, sleep_min, protein_g, water_ml, sources) VALUES ('evilpotato345@gmail.com', '2026-08-05', 360, NULL, NULL, '{"sleep":"manual"}'::jsonb) ON CONFLICT (user_id, date) DO NOTHING;

WITH s AS (
  INSERT INTO sessions (user_id, date, session_name, session_type, notes, status, week_number, block_number)
  SELECT 'evilpotato345@gmail.com', '2026-08-10', 'Session A · Legs & Shoulders', 'A', 'Calibration. Romanian deadlift skipped (3rd consecutive Session A); leg extension not done; no post-session cardio. 6 of 8 first sets landed at 15 reps — systematic underloading. Right knee: pain at depth on hack squat. Garmin: 63:45, avg HR 125, max 154, 334 kcal.', 'DONE', 1, '1'
  WHERE NOT EXISTS (SELECT 1 FROM sessions WHERE user_id = 'evilpotato345@gmail.com' AND date = '2026-08-10' AND session_type = 'A')
  RETURNING id
)
INSERT INTO session_exercises (session_id, exercise_id, sets, reps, weight, set_details, rpe, notes, order_index)
SELECT s.id, (SELECT id FROM exercises WHERE name = v.name AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1), v.sets, v.reps, v.weight::numeric, v.details::jsonb, v.rpe::numeric, v.notes, v.ord
FROM s CROSS JOIN (VALUES
  ('Machine Shoulder Press', 3, 15, 20.00, '[{"reps":15,"weight":20,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":15,"weight":20,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":12,"weight":20,"platesKg":null,"rpe":6,"type":"working","flags":["underloaded"]}]', 6, 'Far too light — never loaded up across 3 sets.', 0),
  ('Hack Squat (machine)', 3, 17, 50.00, '[{"reps":17,"weight":40,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":12,"weight":40,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":8,"weight":50,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, 'Knee pain at depth, ROM cut short. RPE 6–8.', 1),
  ('Leg Press', 3, 12, 213.00, '[{"reps":12,"weight":173,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":173,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":213,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, 'Added after hack squat was cut short.', 2),
  ('Machine Lateral Raise', 3, 15, 25.00, '[{"reps":15,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":15,"weight":20,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":13,"weight":25,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, 'Good live self-correction upward.', 3),
  ('Leg Curl (lying)', 3, 15, 32.00, '[{"reps":15,"weight":25,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":15,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":32,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, 'Set 1 too light.', 4),
  ('Rear Delt Fly (machine)', 3, 15, 35.00, '[{"reps":15,"weight":27.5,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":12,"weight":27.5,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":11,"weight":35,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, 'First time programmed.', 5),
  ('Standing Calf Raise', 3, 12, 35.00, '[{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":35,"platesKg":null,"rpe":7,"type":"working","flags":[]}]', 7, 'Flat, no top-set push.', 6),
  ('Machine Shrugs', 3, 12, 35.00, '[{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":35,"platesKg":null,"rpe":7,"type":"working","flags":[]}]', 7, 'Wrist-safe substitution.', 7)
) AS v(name, sets, reps, weight, details, rpe, notes, ord);

INSERT INTO daily_check_ins (user_id, date, sleep_min, protein_g, water_ml, sources) VALUES ('evilpotato345@gmail.com', '2026-08-10', 350, 150, 3500, '{"sleep":"manual","protein":"manual","water":"manual"}'::jsonb) ON CONFLICT (user_id, date) DO NOTHING;

WITH s AS (
  INSERT INTO sessions (user_id, date, session_name, session_type, notes, status, week_number, block_number)
  SELECT 'evilpotato345@gmail.com', '2026-08-12', 'Session B · Back & Biceps', 'B', 'Deadlift 80×5 hit — 85 next cycle. Reverse barbell curl: second TFCC violation, retired for good. Grip (not biceps) ended the curls — straps on deadlifts and rows. Dead hang programmed, skipped. Sleep 5 h + 2 h nap (fragmented). Protein 120 g at logging, dinner outstanding. 3 g L-citrulline pre. Whoop/Strava: 59:39, 317 kcal, avg HR 117.', 'DONE', 1, '1'
  WHERE NOT EXISTS (SELECT 1 FROM sessions WHERE user_id = 'evilpotato345@gmail.com' AND date = '2026-08-12' AND session_type = 'B')
  RETURNING id
)
INSERT INTO session_exercises (session_id, exercise_id, sets, reps, weight, set_details, rpe, notes, order_index)
SELECT s.id, (SELECT id FROM exercises WHERE name = v.name AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1), v.sets, v.reps, v.weight::numeric, v.details::jsonb, v.rpe::numeric, v.notes, v.ord
FROM s CROSS JOIN (VALUES
  ('Assisted Pull-Up', 3, 10, 54.00, '[{"reps":10,"weight":54,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":6,"weight":47,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":5,"weight":47,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, 'Set 1 still a warm-up — open at 47.', 0),
  ('Barbell Deadlift', 3, 12, 80.00, '[{"reps":12,"weight":60,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":70,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":5,"weight":80,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, 'First time in 3 cycles — top set as prescribed.', 1),
  ('Preacher Curl (rotating handles)', 3, 12, 30.00, '[{"reps":12,"weight":23,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":6,"weight":30,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":5,"weight":30,"platesKg":null,"rpe":9,"type":"working","flags":[]}]', 9, '23 too light; 30 is the new baseline. RPE 8–9.', 2),
  ('Lat Pulldown (wide)', 3, 13, 47.00, '[{"reps":13,"weight":40,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":8,"weight":47,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":8,"weight":47,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, NULL, 3),
  ('Cable Curl', 3, 8, 17.50, '[{"reps":7,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":8,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":4,"weight":17.5,"platesKg":null,"rpe":9,"type":"working","flags":[]}]', 9, 'Grip-limited, not bicep-limited. Set 3 was 4.5 reps.', 4),
  ('Seated Cable Row', 3, 12, 57.00, '[{"reps":12,"weight":47,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":7,"weight":57,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":8,"weight":57,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, 'Replaced machine row + chest-supported row.', 5),
  ('Reverse Barbell Curl', 3, 12, 17.50, '[{"reps":12,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":["blocked_override"]},{"reps":12,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":["blocked_override"]},{"reps":7,"weight":17.5,"platesKg":null,"rpe":null,"type":"working","flags":["blocked_override"]}]', NULL, 'PROHIBITED — TFCC. Second logged violation.', 6),
  ('Forearm / Wrist Curl', 3, 20, 10.00, '[{"reps":20,"weight":0,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":10,"weight":10,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":10,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, NULL, 7)
) AS v(name, sets, reps, weight, details, rpe, notes, ord);

INSERT INTO daily_check_ins (user_id, date, sleep_min, protein_g, water_ml, sources) VALUES ('evilpotato345@gmail.com', '2026-08-12', 300, 120, 3000, '{"sleep":"manual","protein":"manual","water":"manual"}'::jsonb) ON CONFLICT (user_id, date) DO NOTHING;

WITH s AS (
  INSERT INTO sessions (user_id, date, session_name, session_type, notes, status, week_number, block_number)
  SELECT 'evilpotato345@gmail.com', '2026-08-13', 'Session C · Chest, Triceps & Core', 'C', 'Carriage weights discovered mid-session (true load = plates + carriage). Key error: chest and triceps alternated set-for-set, so pushdowns pre-fatigued the press (10 → 4.5 collapse). Fix: alternate chest with core, triceps as a block at the end. Chest fly and plank skipped. 5 min incline walk (8°, 5 km/h, HR 120–140). Next C: horizontal 30.7 hold, decline 30.2, incline 21.1, tricep press 65, rope pushdown 30 (last), torso rotation 45.', 'DONE', 1, '1'
  WHERE NOT EXISTS (SELECT 1 FROM sessions WHERE user_id = 'evilpotato345@gmail.com' AND date = '2026-08-13' AND session_type = 'C')
  RETURNING id
)
INSERT INTO session_exercises (session_id, exercise_id, sets, reps, weight, set_details, rpe, notes, order_index)
SELECT s.id, (SELECT id FROM exercises WHERE name = v.name AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1), v.sets, v.reps, v.weight::numeric, v.details::jsonb, v.rpe::numeric, v.notes, v.ord
FROM s CROSS JOIN (VALUES
  ('Iso-Lateral Horizontal Press', 4, 10, 30.70, '[{"reps":10,"weight":30.7,"platesKg":22.5,"rpe":null,"type":"working","flags":["top_set_pr"]},{"reps":8,"weight":30.7,"platesKg":22.5,"rpe":null,"type":"working","flags":["top_set_pr"]},{"reps":4,"weight":30.7,"platesKg":22.5,"rpe":null,"type":"working","flags":["top_set_pr"]},{"reps":5,"weight":30.7,"platesKg":22.5,"rpe":9.5,"type":"working","flags":["top_set_pr"]}]', 9.5, '22.5 plates + 8.2 carriage. Set 3 was 4.5 reps.', 0),
  ('Rope Pushdown', 3, 12, 27.50, '[{"reps":12,"weight":27.5,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]},{"reps":12,"weight":27.5,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]},{"reps":9,"weight":27.5,"platesKg":null,"rpe":8,"type":"working","flags":["top_set_pr"]}]', 8, 'Done first, alternated into chest work.', 1),
  ('Iso-Lateral Decline Press', 3, 10, 27.70, '[{"reps":10,"weight":27.7,"platesKg":25,"rpe":null,"type":"working","flags":[]},{"reps":8,"weight":27.7,"platesKg":25,"rpe":null,"type":"working","flags":[]},{"reps":7,"weight":27.7,"platesKg":25,"rpe":8,"type":"working","flags":[]}]', 8, '25 plates + 2.7 carriage. Clean curve.', 2),
  ('Machine Tricep Press', 3, 10, 57.50, '[{"reps":10,"weight":57.5,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":57.5,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":8,"weight":57.5,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, 'Stack has no 60 — next increment is 65.', 3),
  ('Iso-Lateral Incline Press', 4, 10, 21.10, '[{"reps":10,"weight":18.6,"platesKg":15,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":3,"weight":21.1,"platesKg":17.5,"rpe":null,"type":"working","flags":[]},{"reps":3,"weight":18.6,"platesKg":15,"rpe":null,"type":"working","flags":[]},{"reps":6,"weight":18.6,"platesKg":15,"rpe":9,"type":"working","flags":[]}]', 9, 'Set 2 attempted 21.1/side for 3, dropped back to 18.6.', 4),
  ('Machine Torso Rotation', 2, 12, 42.50, '[{"reps":12,"weight":42.5,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":42.5,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, '12 per side, top of range both sets.', 5),
  ('Ab Crunch (Matrix)', 2, 10, 27.00, '[{"reps":10,"weight":27,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":27,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, NULL, 6),
  ('Ab Crunch (Life Fitness)', 2, 10, 27.50, '[{"reps":10,"weight":27.5,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":27.5,"platesKg":null,"rpe":8,"type":"working","flags":[]}]', 8, NULL, 7)
) AS v(name, sets, reps, weight, details, rpe, notes, ord);

WITH s AS (
  INSERT INTO sessions (user_id, date, session_name, session_type, notes, status, week_number, block_number)
  SELECT 'evilpotato345@gmail.com', '2026-08-17', 'Session A · Legs & Shoulders', 'A', 'Big loading day — first session with no first-set underloading. Undermined by 4 h sleep and a 42 g protein shortfall. RDL not performed (machine variant attempted, form broke down) — third consecutive skip. Hamstring failed leg curl set 3. Shrugs moved to Session B at 25 kg minimum. Leg press: add load on set 2.', 'DONE', 1, '1'
  WHERE NOT EXISTS (SELECT 1 FROM sessions WHERE user_id = 'evilpotato345@gmail.com' AND date = '2026-08-17' AND session_type = 'A')
  RETURNING id
)
INSERT INTO session_exercises (session_id, exercise_id, sets, reps, weight, set_details, rpe, notes, order_index)
SELECT s.id, (SELECT id FROM exercises WHERE name = v.name AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1), v.sets, v.reps, v.weight::numeric, v.details::jsonb, v.rpe::numeric, v.notes, v.ord
FROM s CROSS JOIN (VALUES
  ('Machine Shoulder Press', 3, 12, 35.00, '[{"reps":12,"weight":27.5,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]},{"reps":10,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]},{"reps":8,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]}]', NULL, 'Opened at prescribed 27.5, jumped to 35.', 0),
  ('Machine Squat', 3, 12, 90.00, '[{"reps":12,"weight":60,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":70,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":90,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Right knee — monitor depth at 90. 50 → 90 in a week: confirm.', 1),
  ('Machine Lateral Raise', 3, 15, 39.00, '[{"reps":15,"weight":27.5,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":12,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":9,"weight":39,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]}]', NULL, 'Strong progression.', 2),
  ('Leg Press', 3, 12, 233.00, '[{"reps":12,"weight":233,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]},{"reps":12,"weight":233,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]},{"reps":12,"weight":233,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]}]', NULL, 'No load change across sets — test up next time.', 3),
  ('Rear Delt Fly (machine)', 3, 12, 42.50, '[{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":9,"weight":42.5,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]},{"reps":9,"weight":42.5,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]}]', NULL, NULL, 4),
  ('Leg Curl (lying)', 2, 15, 46.00, '[{"reps":15,"weight":39,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":10,"weight":46,"platesKg":null,"rpe":null,"type":"working","flags":["top_set_pr"]}]', NULL, 'Hamstring failed set 3 — stopped.', 5),
  ('Machine Shrugs', 3, 10, 15.00, '[{"reps":10,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":10,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":10,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]}]', NULL, 'Underloaded (floor is 25). Removed from Session A.', 6),
  ('Seated Calf Raise', 3, 10, 47.30, '[{"reps":6,"weight":47.3,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":37.3,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":37.3,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Overshot set 1, corrected down.', 7)
) AS v(name, sets, reps, weight, details, rpe, notes, ord);

INSERT INTO daily_check_ins (user_id, date, sleep_min, protein_g, water_ml, sources) VALUES ('evilpotato345@gmail.com', '2026-08-17', 240, 113, 3000, '{"sleep":"manual","protein":"manual","water":"manual"}'::jsonb) ON CONFLICT (user_id, date) DO NOTHING;

WITH s AS (
  INSERT INTO sessions (user_id, date, session_name, session_type, notes, status, week_number, block_number)
  SELECT 'evilpotato345@gmail.com', '2026-08-24', 'Session A · Legs & Shoulders', 'A', 'Leg extension back in rotation. Shoulder press and rear delt fly regressed vs 17/08 — likely sleep (5h20) and protein (110 g). DB RDL not performed — fourth consecutive skip. Shrugs back in Session A at the underloaded weight.', 'DONE', 1, '1'
  WHERE NOT EXISTS (SELECT 1 FROM sessions WHERE user_id = 'evilpotato345@gmail.com' AND date = '2026-08-24' AND session_type = 'A')
  RETURNING id
)
INSERT INTO session_exercises (session_id, exercise_id, sets, reps, weight, set_details, rpe, notes, order_index)
SELECT s.id, (SELECT id FROM exercises WHERE name = v.name AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1), v.sets, v.reps, v.weight::numeric, v.details::jsonb, v.rpe::numeric, v.notes, v.ord
FROM s CROSS JOIN (VALUES
  ('Machine Shoulder Press', 3, 8, 32.00, '[{"reps":8,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":8,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":6,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Down from 35 on 17/08.', 0),
  ('Barbell Back Squat', 3, 8, 70.00, '[{"reps":8,"weight":60,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":6,"weight":70,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":6,"weight":70,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'No reported knee issue — watch depth.', 1),
  ('Machine Lateral Raise', 3, 12, 39.00, '[{"reps":8,"weight":39,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":8,"weight":39,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]}]', NULL, NULL, 2),
  ('Leg Extension (machine)', 3, 15, 68.00, '[{"reps":15,"weight":54,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":12,"weight":61,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":9,"weight":68,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'First time since the gap flagged 10/08. Set 1 opened light.', 3),
  ('Rear Delt Fly (machine)', 3, 12, 35.00, '[{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":9,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]}]', NULL, 'Down from 42.5 on 17/08.', 4),
  ('Leg Curl (lying)', 2, 15, 39.00, '[{"reps":15,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":12,"weight":39,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]}]', NULL, 'Conservative restart after the 17/08 hamstring failure.', 5),
  ('Standing Calf Raise', 3, 12, 35.00, '[{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Flat, no top-set push.', 6),
  ('Machine Shrugs', 3, 15, 15.00, '[{"reps":15,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":15,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":15,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Below the 25 kg floor, wrong session.', 7)
) AS v(name, sets, reps, weight, details, rpe, notes, ord);

INSERT INTO daily_check_ins (user_id, date, sleep_min, protein_g, water_ml, sources) VALUES ('evilpotato345@gmail.com', '2026-08-24', 320, 110, 2500, '{"sleep":"manual","protein":"manual","water":"manual"}'::jsonb) ON CONFLICT (user_id, date) DO NOTHING;

WITH s AS (
  INSERT INTO sessions (user_id, date, session_name, session_type, notes, status, week_number, block_number)
  SELECT 'evilpotato345@gmail.com', '2026-08-26', 'Session B · Back & Biceps (home)', 'B', 'HOME — Bangalore, dumbbells up to 16 kg, incline bench. Maintenance load: not comparable to Al Reef weights. Skipped: bent-over DB row, DB shrugs, incline DB curl (16 of 25 sets). DB row ceiling hit at 16×15×3 — progress via tempo next time. Hammer curls grip-limited (third time) — run them first. Nutrition and sleep not logged.', 'DONE', 1, '1'
  WHERE NOT EXISTS (SELECT 1 FROM sessions WHERE user_id = 'evilpotato345@gmail.com' AND date = '2026-08-26' AND session_type = 'B')
  RETURNING id
)
INSERT INTO session_exercises (session_id, exercise_id, sets, reps, weight, set_details, rpe, notes, order_index)
SELECT s.id, (SELECT id FROM exercises WHERE name = v.name AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1), v.sets, v.reps, v.weight::numeric, v.details::jsonb, v.rpe::numeric, v.notes, v.ord
FROM s CROSS JOIN (VALUES
  ('Dumbbell Row', 3, 15, 16.00, '[{"reps":15,"weight":16,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":15,"weight":16,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":15,"weight":16,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Single-arm, 15/side all sets. Ceiling hit at max available load.', 0),
  ('DB Pullover', 3, 15, 14.50, '[{"reps":15,"weight":10,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":12,"weight":12,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":14.5,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Clean ascending load — start at 14.5 next time.', 1),
  ('Chest Supported Row', 3, 12, 12.00, '[{"reps":12,"weight":12,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":12,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":12,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Incline DB, programmed at 2×16 — ran at 12.', 2),
  ('Dumbbell Curl', 3, 12, 12.00, '[{"reps":12,"weight":10,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":8,"weight":12,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":8,"weight":12,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Standing. Opened at 10, corrected up.', 3),
  ('Hammer Curl (DB)', 4, 12, 12.00, '[{"reps":12,"weight":10,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":5,"weight":12,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":8,"weight":10,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":6,"weight":10,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, '12 collapsed to 5 — grip fatigue after 3 gripping movements.', 4)
) AS v(name, sets, reps, weight, details, rpe, notes, ord);

WITH s AS (
  INSERT INTO sessions (user_id, date, session_name, session_type, notes, status, week_number, block_number)
  SELECT 'evilpotato345@gmail.com', '2026-09-21', 'Session A · Legs & Shoulders', 'A', 'Re-entry (first gym Session A since 24/08). 7 min treadmill run at 8.5 km/h pre-lift. DB RDL performed for the first time — lower back pain within 5 min; removed from the programme (lumbar irritation logged 19/08). Barbell squat swapped for leg press. Next: leg press 232 → 240 → 250; shoulder press hold 32 until 3×10; leg extension 61 → 68 → 68 for 12s; calf raise open at 35, 3×12 with 3 s eccentric.', 'DONE', 1, '1'
  WHERE NOT EXISTS (SELECT 1 FROM sessions WHERE user_id = 'evilpotato345@gmail.com' AND date = '2026-09-21' AND session_type = 'A')
  RETURNING id
)
INSERT INTO session_exercises (session_id, exercise_id, sets, reps, weight, set_details, rpe, notes, order_index)
SELECT s.id, (SELECT id FROM exercises WHERE name = v.name AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1), v.sets, v.reps, v.weight::numeric, v.details::jsonb, v.rpe::numeric, v.notes, v.ord
FROM s CROSS JOIN (VALUES
  ('DB Romanian Deadlift', 3, 10, 16.00, '[{"reps":10,"weight":16,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":16,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":16,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, '2 × 16 kg DBs. Lower back pain within 5 min — removed.', 0),
  ('Machine Shoulder Press', 3, 8, 32.00, '[{"reps":8,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":8,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":6,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Identical to 24/08 — stalled.', 1),
  ('Leg Press', 3, 12, 232.00, '[{"reps":12,"weight":232,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":232,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":232,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Same load all sets — third time flagged.', 2),
  ('Machine Lateral Raise', 4, 10, 39.00, '[{"reps":10,"weight":39,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":6,"weight":39,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":3,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":8,"weight":32,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]}]', NULL, 'Read from a handwritten log — confirm. Sharp fade after set 1.', 3),
  ('Leg Extension (machine)', 3, 15, 68.00, '[{"reps":15,"weight":54,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]},{"reps":12,"weight":61,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":68,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, '68 × 9 → 68 × 12. Set 1 still opens light.', 4),
  ('Standing Calf Raise', 3, 12, 35.00, '[{"reps":10,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":10,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":27,"platesKg":null,"rpe":null,"type":"working","flags":["underloaded"]}]', NULL, 'Prescribed 40 — not attempted. Dropped load set 3.', 5),
  ('Rear Delt Fly (machine)', 2, 12, 35.00, '[{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]},{"reps":12,"weight":35,"platesKg":null,"rpe":null,"type":"working","flags":[]}]', NULL, 'Optional add-on, 2 sets as agreed.', 6)
) AS v(name, sets, reps, weight, details, rpe, notes, ord);

INSERT INTO daily_check_ins (user_id, date, sleep_min, protein_g, water_ml, sources) VALUES ('evilpotato345@gmail.com', '2026-09-21', 360, 110, 2000, '{"sleep":"manual","protein":"manual","water":"manual"}'::jsonb) ON CONFLICT (user_id, date) DO NOTHING;

INSERT INTO coach_flags (user_id, text, scope, scope_value, created_by) SELECT 'evilpotato345@gmail.com', 'Open heavier. First sets keep landing light — correct within the session, not across three.', 'global', NULL, 'user' WHERE NOT EXISTS (SELECT 1 FROM coach_flags WHERE user_id = 'evilpotato345@gmail.com' AND text = 'Open heavier. First sets keep landing light — correct within the session, not across three.');

INSERT INTO coach_flags (user_id, text, scope, scope_value, created_by) SELECT 'evilpotato345@gmail.com', 'Sleep and the 155 g protein floor are the primary limiters, unaddressed across every recent session.', 'global', NULL, 'user' WHERE NOT EXISTS (SELECT 1 FROM coach_flags WHERE user_id = 'evilpotato345@gmail.com' AND text = 'Sleep and the 155 g protein floor are the primary limiters, unaddressed across every recent session.');

INSERT INTO coach_flags (user_id, text, scope, scope_value, created_by) SELECT 'evilpotato345@gmail.com', 'Back: no loaded spinal hinging in any session until symptom-free (deadlifts of every kind, RDL, good morning, bent-over or Pendlay row, back extension). Leg curl goes first, calibrate hip thrust / glute bridge.', 'global', NULL, 'user' WHERE NOT EXISTS (SELECT 1 FROM coach_flags WHERE user_id = 'evilpotato345@gmail.com' AND text = 'Back: no loaded spinal hinging in any session until symptom-free (deadlifts of every kind, RDL, good morning, bent-over or Pendlay row, back extension). Leg curl goes first, calibrate hip thrust / glute bridge.');

INSERT INTO coach_flags (user_id, text, scope, scope_value, created_by) SELECT 'evilpotato345@gmail.com', 'Straps on deadlifts and rows — grip quits before the back does.', 'sessionType', 'B', 'user' WHERE NOT EXISTS (SELECT 1 FROM coach_flags WHERE user_id = 'evilpotato345@gmail.com' AND text = 'Straps on deadlifts and rows — grip quits before the back does.');

INSERT INTO coach_flags (user_id, text, scope, scope_value, created_by) SELECT 'evilpotato345@gmail.com', 'Add load on set 2: 232 → 240 → 250.', 'exerciseId', (SELECT id FROM exercises WHERE name = 'Leg Press' AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1)::text, 'user' WHERE NOT EXISTS (SELECT 1 FROM coach_flags WHERE user_id = 'evilpotato345@gmail.com' AND text = 'Add load on set 2: 232 → 240 → 250.');

INSERT INTO coach_flags (user_id, text, scope, scope_value, created_by) SELECT 'evilpotato345@gmail.com', 'Stalled at 32 × 8, 8, 6. Hold 32 and hit 3 × 10 before moving to 35.', 'exerciseId', (SELECT id FROM exercises WHERE name = 'Machine Shoulder Press' AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1)::text, 'user' WHERE NOT EXISTS (SELECT 1 FROM coach_flags WHERE user_id = 'evilpotato345@gmail.com' AND text = 'Stalled at 32 × 8, 8, 6. Hold 32 and hit 3 × 10 before moving to 35.');

INSERT INTO coach_flags (user_id, text, scope, scope_value, created_by) SELECT 'evilpotato345@gmail.com', 'Lives in Session B. Open at 25 kg minimum, first or second in the order.', 'exerciseId', (SELECT id FROM exercises WHERE name = 'Machine Shrugs' AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1)::text, 'user' WHERE NOT EXISTS (SELECT 1 FROM coach_flags WHERE user_id = 'evilpotato345@gmail.com' AND text = 'Lives in Session B. Open at 25 kg minimum, first or second in the order.');

INSERT INTO coach_flags (user_id, text, scope, scope_value, created_by) SELECT 'evilpotato345@gmail.com', 'Right knee: depth under load is the historical trigger. Leg press is the primary quad compound if it flares.', 'exerciseId', (SELECT id FROM exercises WHERE name = 'Machine Squat' AND created_by IS NULL ORDER BY slug NULLS LAST LIMIT 1)::text, 'user' WHERE NOT EXISTS (SELECT 1 FROM coach_flags WHERE user_id = 'evilpotato345@gmail.com' AND text = 'Right knee: depth under load is the historical trigger. Leg press is the primary quad compound if it flares.');
